---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "kibana.fullname" . }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4}}
{{- end }}
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- range $key, $value := .Values.commonAnnotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
{{- with .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml . | indent 4 }}
{{- end }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
{{- if .nodePort }}
      nodePort: {{ .nodePort }}
{{- end }}
      protocol: TCP
      name: {{ .name }}
{{- if .targetPort }}
      targetPort: {{ .targetPort }}
{{- else }}
      targetPort: {{ .Values.httpPort }}
{{- end }}
  {{- end }}
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name | quote }}
